### ISSUE TITLE
Add E2E tests for support for SignalsHandler

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/quarkus-hilla#815]
A new `SignalsHandler` bean has been added to Hilla, but the extension is not exposing.

```
Error:    CrudRepositoryServiceTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: ]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.vaadin.hilla.signals.core.SignalsRegistry and qualifiers [@Default]
	- injection target: parameter 'registry' of com.vaadin.hilla.signals.handler.SignalsHandler constructor
	- declared on CLASS bean [types=[com.vaadin.hilla.signals.handler.SignalsHandler, java.lang.Object], qualifiers=[@Default, @Any], target=com.vaadin.hilla.signals.handler.SignalsHandler]
	The following classes match by type, but have been skipped during discovery:
	- com.vaadin.hilla.signals.core.SignalsRegistry has no bean defining annotation (scope, stereotype, etc.)


	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1546)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.vaadin.hilla.signals.core.SignalsRegistry and qualifiers [@Default]
	- injection target: parameter 'registry' of com.vaadin.hilla.signals.handler.SignalsHandler constructor
	- declared on CLASS bean [types=[com.vaadin.hilla.signals.handler.SignalsHandler, java.lang.Object], qualifiers=[@Default, @Any], target=com.vaadin.hilla.signals.handler.SignalsHandler]
	The following classes match by type, but have been skipped during discovery:
	- com.vaadin.hilla.signals.core.SignalsRegistry has no bean defining annotation (scope, stereotype, etc.)


	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
	... 14 more
```

**Comment by mcollovati** [comment]
The error has been fixed by #824.
However, E2E tests for full-stack signals should be added.
